### ISSUE TITLE
Laggy player movement with ne camera component

### ISSUE THREAD

**Issue by KurtLa** [flame-engine/flame#2583]
# Current bug behavior
The movement is laggy. I the camera itself moves smooth, but not the player.

![movement_issue](https://github.com/flame-engine/flame/assets/9027932/bfbe8cf1-bd6a-4c46-80de-a17462f8ed2b)

# Expected behavior
Since moving to the new camera component creates this, the same smooth movement like the old system.

# Steps to reproduce
You can use my repository to reproduce it:
https://bitbucket.org/Jinairu/islandsurvivor_bugs/src/master/
it seems to be at least ok in chrome, but its hard on native mac

clone, flutter pub get, run 
use W, A, S, D to navigate

# Flutter doctor output
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.2, on macOS 13.2.1 22D68 darwin-arm64, locale en-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.79.2)
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!

# More environment information
Flame version: 1.8.0
Platform affected: web, osx
Platform version affected: osx 13.2

**Comment by ufrshubham** [comment]
Possibly a duplicate of #2574

**Comment by KurtLa** [comment]
> Reference

Could be the same underlying problem, but my camera runs smoothly and moves flawlessly, only the player jitters.

**Comment by ufrshubham** [comment]
It is very likely that this is same as the one I mentioned earlier. Both the example code were identical in terms of the camera setup.

Can you try testing your code by depending on the `main` branch of flame from GitHub? The original issue is fixed in main 🙂

To depend on `main`, replace your flame entry with the following entry in your `pubspec.yaml` file:
```yaml
dependencies:
  flame:
    git:
      url: https://github.com/flame-engine/flame.git
      ref: main
      path: packages/flame
```

**Comment by KurtLa** [comment]
I have done flutter clean before, but unfortunately the problem is persistent.
![movement_issue2](https://github.com/flame-engine/flame/assets/9027932/2ce44470-1670-423c-99d5-aa1a18734a93)

**Comment by spydon** [comment]
@KurtLa are you still experiencing this?

**Comment by eprivacy-org** [comment]
@spydon 
Thank you for getting back to me. 
The issue still persists in the debug program I mentioned (also with 1.8.2). As suggested, I added `cameraComponent.priority = 1;` and then the problem disappeared.

**Comment by spydon** [comment]
@eprivacy-org did you try with `main`?
```dart
dependencies:
  flame:
    git:
      url: https://github.com/flame-engine/flame.git
      ref: main
      path: packages/flame
```

**Comment by KurtLa** [comment]
@spydon 
Sorry, I commented using the wrong account.

> @spydon Thank you for getting back to me. The issue still persists in the debug program I mentioned (also with version 1.8.2). As suggested, I added cameraComponent.priority = 1; and then the problem disappeared.

No, using the following:

```
flame:
  git:
    url: https://github.com/flame-engine/flame.git
    ref: main
    path: packages/flame
```
and commenting out `// cameraComponent.priority = 1;` leads to the same tremble.

**Comment by spydon** [comment]
Daaamn, that was a deep rabbit hole.

I thought it was due to a recent bug that had been discovered in OrderedSet (the data structure that backs `children` and priority) so I went in and fixed up that repository and released a new version of that, but that did not make any difference at all to your project.
Then I cut everything away from your project until I just had a moving circle and your `InputKeyboard` class and then it hit me, it is not the priority of the `CameraComponent` that is the issue. It is the `priority` of your `InputKeyboard` class, because that one of course has to update all the positions before the rendering starts (which the `CameraComponent` is responsible for triggering).

So set the `priority` of `InputKeyboard` to `-1` and your problem is gone. :)
