### ISSUE TITLE
Flame 1.0.0-rc8 Tap regions off

### ISSUE THREAD

**Issue by nateonguitar** [flame-engine/flame#705]
First of all, thank you for working on this game framework, it's really awesome!

I am trying out `1.0.0-rc8` with Flutter `2.0.3` (but I was having the issue with my game right before Flutter 2.0 released, no change in behavior pre-2.0)

The bug:
If the camera is moved, tappable items stay in the same place on the screen even though the camera moves and the object draws relative to where the camera is.  Drawing relative fine, tapping relative bad.

This is a little difficult to explain.

If `foo` is in position (100, 100) and the `camera` is at the origin (0, 0) the tap regions are normal, you can tap on your object and it registers.

If `foo` is in position (100, 100) and the `camera` is at position(200, 200), you can still tap around physical (100, 100) on your phone and trigger the tap, if you tap on the object you see (translated from the camera move), no tap is registered.

I made an unlisted YouTube video showing this behavior:
https://youtu.be/n3L1GG3wmvo

A similar behavior happens when the anchor point is not in the center.  The video shows this as well.

Source code to play with

```
import 'package:flame/components.dart';
import 'package:flame/game.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(App());
}

class App extends StatelessWidget {
  final GameManager gameManager = GameManager();
  @override
  Widget build(BuildContext context) {
    return GameWidget(game: gameManager);
  }
}

class GameManager extends BaseGame with HasTapableComponents {

  Tile tapMeTile = Tile(Color(0xFF0000FF));
  Tile cameraFollowTile = Tile(Color(0xFF800080));

  @override
  Future<void> onLoad() {
    tapMeTile.position = Vector2(200, 200);
    cameraFollowTile.position = Vector2(100, 100);
    add(tapMeTile);
    add(cameraFollowTile);
    // camera.follow = cameraFollowTile;
    return super.onLoad();
  }
}

class Tile extends PositionComponent with Tapable {

  bool toggle = false;
  Color untappedColor;

  Tile(Color untappedColor) {
    size = Vector2(50, 50);
    this.untappedColor = untappedColor;
    // anchor = Anchor.center;
  }

  @override
  bool onTapDown(TapDownDetails details) {
    toggle = !toggle;
    return true;
  }

  @override
  void render(Canvas canvas) {
    Rect rect = Rect.fromCircle(
      center: position.toOffset(),
      radius: size.x/2,
    );
    canvas.drawRect(rect, paint());
    super.render(canvas);
  }

  Paint paint() {
    Color color = toggle ? Color(0xFF00FF00) : untappedColor;
    return Paint()..color = color;
  }
}
```

pubspec.yml

```
name: flame_test_ontap
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flame: 1.0.0-rc8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
```

**Comment by luanpotter** [comment]
Hi @nateonguitar , thanks for reporting this!

This was actually a known side effect of the interaction of camera/viewport + tapables. I proposed a list of solutions on [the original PR](https://github.com/flame-engine/flame/pull/673), you can take a look there it describes what exactly the issue is and how to hack a solution (using the provided transform functions).

We landed on implementing option 4, which involves redefining all event classes on our side, but I haven't gotten to it yet. Hopefully I will have something ready soon! In the meanwhile, sorry for the inconvenience.

**Comment by nateonguitar** [comment]
Oh dude! I'm excited to see the outcome!

I just skimmed through the other thread, is the anchor position with the tap regions also a known issue?

**Comment by spydon** [comment]
> Oh dude! I'm excited to see the outcome!
> 
> I just skimmed through the other thread, is the anchor position with the tap regions also a known issue?

Is that a new bug for rc8 too? The tap regions and anchors should have been working in rc7 at least. I will have a look later!

**Comment by luanpotter** [comment]
Watching the video, there is definitely a bug with anchor as well if you can take a look @spydon

**Comment by nateonguitar** [comment]
I just tested with `1.0.0-rc8` and yes, both the camera move offset and anchor offsets have the same results as my `rc7` test.

**Comment by spydon** [comment]
I have found the issue with the anchors, I will hopefully have a PR up later today.

**Comment by erickzanardo** [comment]
Fixed on #710

**Comment by nateonguitar** [comment]
Awesome, thanks for working in this!

**Comment by nateonguitar** [comment]
Hi guys, first of all, thanks for working on this, I'm excited to see where Flame is headed for v1.0 release!

@erickzanardo @luanpotter @spydon

I think this issue might have been closed prematurely.  Here's a video of the issue still happening.  Before making the video I used `rc8` and the issue was still there, but I know you guys have done a lot of work since then.  When I point at `main` in github the issue still happens.

The code is identical to what I posted earlier except instead of `camera.follow = obj` I used `camera.followComponent(obj)` and I changed the line in pubspec.yaml to use github instead using 

```
  # flame: 1.0.0-rc8
  
  flame:
    git:
      url: https://github.com/flame-engine/flame.git
      path: packages/flame
      ref: main
```

https://youtu.be/SxAjdFY_EcU

**Comment by nateonguitar** [comment]
Also, I'd like to mention, I have no pre-1.0 experience with Flame.  I saw that version 1.0 is being worked on so I didn't really care to learn pre-1.0, so if I'm doing anything wrong please let me know, I posted the code above.  If this can be fixed with some documentation update that's a lot easier than fixing it when it does actually work if I used it correctly.

**Comment by spydon** [comment]
Hey @nateonguitar, you are correct this was closed too early since only one of the the problems were solved (the anchor one), and I don't think we are tracking the new events system (which this depends on) in an issue, right @luanpotter?

**Comment by erickzanardo** [comment]
I am unsure if this is really a problem, we have planned the new event system to be implemented, but at the moment the methods on the camera can be used to get coordinates into the game world right?

**Comment by spydon** [comment]
@erickzanardo I assume the users would think that for example tapable should continue working even if they move the camera?
It's not something the common user would think that they would have to re-implement themselves just because they move the camera I think, and therefore classed as bug?

**Comment by erickzanardo** [comment]
You are right @spydon, I totally forgot about tapbles and draggables

**Comment by nateonguitar** [comment]
Hi guys, just trying our rc9 which says:

![image](https://user-images.githubusercontent.com/19334124/113809055-92a78100-9724-11eb-8276-59f4f82947b2.png)

I just tried out the tap regions for having an anchor not centered and it's the same issue.  I can tap off to the bottom right of the square and it triggers the tap event.  The left and top quadrants don't trigger the tap event as expected when using the default anchor point.

I'm bringing it up again because this is the default anchor position.

**Comment by spydon** [comment]
Hmm, that is odd, I thought I added tests for this after I fixed it.
Just to clarify, this is without moving the camera right?

**Comment by spydon** [comment]
It feels like this example should be broken if it wasn't fixed in rc9:
https://flame-engine.github.io/flame/#/Controls_Tapables :thinking:

**Comment by spydon** [comment]
Ah, I see what the problem is here.
It looks like your `render` function is off:
```dart
  @override
  void render(Canvas canvas) {
    Rect rect = Rect.fromCircle(
      center: position.toOffset(),
      radius: size.x/2,
    );
    canvas.drawRect(rect, paint());
    super.render(canvas);
  }
```

`position` will be the anchor position in there, not the center which you expect. Try this instead:

```dart
  @override
  void render(Canvas canvas) {
    canvas.drawRect(toRect(), paint());
    super.render(canvas);
  }
```

**Comment by nateonguitar** [comment]
@spydon That fixed it!
