### ISSUE TITLE
Hitbox collision between Circle and Rectangle not working

### ISSUE THREAD

**Issue by afonsocarlos** [flame-engine/flame#759]
# Current bug behaviour

`onCollision` method is not being triggered between a `HitboxCircle` and a `HitboxRectangle`.

# Expected behaviour

`onCollision` method should be triggered when a `HitboxCircle` collided with a `HitboxRectangle`.

# Steps to reproduce

A base game example can be found here https://github.com/afonsocarlos/buggy-game as a reference. Just `git clone` it and run.

# Flutter doctor output

```
Output of: flutter doctor -v
[✓] Flutter (Channel stable, 2.0.4, on Linux, locale en_US.UTF-8)
    • Flutter version 2.0.4 at /opt/flutter
    • Framework revision b1395592de (11 days ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/carlos/Android/Sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (2 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 89.0.4389.90

• No issues found!
```

# More environment information

Flame version: 1.0.0-rc9
Platform affected: android
Platform version affected: android 10

# More information

It's also worth noting that it works fine in 1.0.0-rc8. I can try to track and solve the problem if I can have your help

**Comment by spydon** [comment]
I did investigate this a bit today, it doesn't have anything to do with it being a circle, but there is a bug in the collision detection system for sure. Somehow it seems like certain sizes of the hitboxes will make the collision detection not work. I can't understand why it works with all the shapes and sizes in the examples though.
Will continue to investigate.

**Comment by spydon** [comment]
It works like it should in `rc7`, so there was some degradation when we released `rc8`.

**Comment by ufrshubham** [comment]
@spydon just an observation. Setting `position` of Hitbox to it's component's position seems to create the correct behavior. See if this helps to find the exact root cause. Following is a code snippet:

```dart
    final shape = HitboxPolygon([
      Vector2(0, 1),
      Vector2(1, 0),
      Vector2(0, -1),
      Vector2(-1, 0),
    ]);
    shape.position = this.position;
    addShape(shape);
 ```

**Comment by spydon** [comment]
@ufrshubham @afonsocarlos can you try if using the #761 PR branch as a dependency solves your problems? (Seems like there still is an issue with the `ScreenCollidable` though)


If you haven't used a git branch as a dependency before, this is how you do it:
```pubspec
dependencies:
  flame:
    git:
      url: git@github.com:flame-engine/flame.git
      path: packages/flame
      ref: spydon.fix-bounding-rect-check
```

**Comment by ufrshubham** [comment]
I'm still seeing that issue. @afonsocarlos can you confirm. You might have to use the http url while adding dependency.

**Comment by afonsocarlos** [comment]
I couldn't test it yet because of work, but I'll definitely take a look at this tonight

**Comment by spydon** [comment]
I made some optimizations, and we are back at the original issue.
It seems like rectangle/polygon collisions doesn't work against each other like they should, like you said.
HitboxCircle with HitboxRectangle seems to work.
Trying to fix it now.

**Comment by spydon** [comment]
That was such a silly mistake (the cache invalidation for the HitboxPolygon wasn't working), it should be working now. :)
Would be great if you can verify with your own applications!

**Comment by ufrshubham** [comment]
Cool! I'll test it again ASAP.

**Comment by afonsocarlos** [comment]
It worked perfectly! Thanks @spydon :rocket:

**Comment by spydon** [comment]
Glad to hear it! I merged the PR now, so you can depend on `main` instead of my branch until we release `rc10` which should be later this week.

**Comment by camillo777** [comment]
Hello, yes I can confirm it is working also with the diamond shape!
